// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Two tools cover the entire API: <api>_search to discover endpoints, and
// <api>_execute to invoke one. This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search+execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the two agent-facing tools that
// cover the whole API surface. Called from RegisterTools in place of the
// per-endpoint registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("straddle_search",
			mcplib.WithDescription("Search the straddle API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("straddle_execute",
			mcplib.WithDescription("Execute one straddle API endpoint by its endpoint_id (from straddle_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by straddle_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// search+execute pair needs at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	keywords        []string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:         "account-settings.get-settings",
		Method:     "GET",
		Path:       "/v1/account_settings/{account_id}",
		Summary:    "Get all resolved settings for the specified account, including inherited values from organization, platform, and...",
		Positional: []string{"account_id"},
		keywords:   codeOrchKeywords("account-settings", "get-settings", "Get all resolved settings for the specified account, including inherited values from organization, platform, and...", "/v1/account_settings/{account_id}"),
	},
	{
		ID:         "accounts.create",
		Method:     "POST",
		Path:       "/v1/accounts",
		Summary:    "Creates a new account associated with your Straddle platform integration. This endpoint allows you to set up an...",
		Positional: []string{},
		keywords:   codeOrchKeywords("accounts", "create", "Creates a new account associated with your Straddle platform integration. This endpoint allows you to set up an...", "/v1/accounts"),
	},
	{
		ID:         "accounts.get",
		Method:     "GET",
		Path:       "/v1/accounts/{account_id}",
		Summary:    "Retrieves the details of an account that has previously been created. Supply the unique account ID that was returned...",
		Positional: []string{"account_id"},
		keywords:   codeOrchKeywords("accounts", "get", "Retrieves the details of an account that has previously been created. Supply the unique account ID that was returned...", "/v1/accounts/{account_id}"),
	},
	{
		ID:         "accounts.list",
		Method:     "GET",
		Path:       "/v1/accounts",
		Summary:    "Returns a list of accounts associated with your Straddle platform integration. The accounts are returned sorted by...",
		Positional: []string{},
		keywords:   codeOrchKeywords("accounts", "list", "Returns a list of accounts associated with your Straddle platform integration. The accounts are returned sorted by...", "/v1/accounts"),
	},
	{
		ID:         "accounts.update",
		Method:     "PUT",
		Path:       "/v1/accounts/{account_id}",
		Summary:    "Updates an existing account's information. This endpoint allows you to update various account details during...",
		Positional: []string{"account_id"},
		keywords:   codeOrchKeywords("accounts", "update", "Updates an existing account's information. This endpoint allows you to update various account details during...", "/v1/accounts/{account_id}"),
	},
	{
		ID:         "accounts.capability-requests.create",
		Method:     "POST",
		Path:       "/v1/accounts/{account_id}/capability_requests",
		Summary:    "Submits a request to enable a specific capability for an account. Use this endpoint to request additional features...",
		Positional: []string{"account_id"},
		keywords:   codeOrchKeywords("accounts", "create", "Submits a request to enable a specific capability for an account. Use this endpoint to request additional features...", "/v1/accounts/{account_id}/capability_requests"),
	},
	{
		ID:         "accounts.capability-requests.list",
		Method:     "GET",
		Path:       "/v1/accounts/{account_id}/capability_requests",
		Summary:    "Retrieves a list of capability requests associated with an account. The requests are returned sorted by creation...",
		Positional: []string{"account_id"},
		keywords:   codeOrchKeywords("accounts", "list", "Retrieves a list of capability requests associated with an account. The requests are returned sorted by creation...", "/v1/accounts/{account_id}/capability_requests"),
	},
	{
		ID:         "accounts.onboard.account",
		Method:     "POST",
		Path:       "/v1/accounts/{account_id}/onboard",
		Summary:    "Initiates the onboarding process for a new account. This endpoint can only be used for accounts where at least one...",
		Positional: []string{"account_id"},
		keywords:   codeOrchKeywords("accounts", "account", "Initiates the onboarding process for a new account. This endpoint can only be used for accounts where at least one...", "/v1/accounts/{account_id}/onboard"),
	},
	{
		ID:         "accounts.simulate.create",
		Method:     "POST",
		Path:       "/v1/accounts/{account_id}/simulate",
		Summary:    "Simulate the status transitions for sandbox accounts. This endpoint can only be used for sandbox accounts.",
		Positional: []string{"account_id"},
		keywords:   codeOrchKeywords("accounts", "create", "Simulate the status transitions for sandbox accounts. This endpoint can only be used for sandbox accounts.", "/v1/accounts/{account_id}/simulate"),
	},
	{
		ID:         "bridge.create",
		Method:     "POST",
		Path:       "/v1/bridge/quiltt",
		Summary:    "Creates a new paykey using a Quiltt token as the source. This endpoint allows you to create a secure payment token...",
		Positional: []string{},
		keywords:   codeOrchKeywords("bridge", "create", "Creates a new paykey using a Quiltt token as the source. This endpoint allows you to create a secure payment token...", "/v1/bridge/quiltt"),
	},
	{
		ID:         "bridge.create-bank-account-paykey",
		Method:     "POST",
		Path:       "/v1/bridge/bank_account",
		Summary:    "Use Bridge to create a new paykey using a bank routing and account number as the source. This endpoint allows you to...",
		Positional: []string{},
		keywords:   codeOrchKeywords("bridge", "create-bank-account-paykey", "Use Bridge to create a new paykey using a bank routing and account number as the source. This endpoint allows you to...", "/v1/bridge/bank_account"),
	},
	{
		ID:         "bridge.create-plaid-paykey",
		Method:     "POST",
		Path:       "/v1/bridge/plaid",
		Summary:    "Use Bridge to create a new paykey using a Plaid token as the source. This endpoint allows you to create a secure...",
		Positional: []string{},
		keywords:   codeOrchKeywords("bridge", "create-plaid-paykey", "Use Bridge to create a new paykey using a Plaid token as the source. This endpoint allows you to create a secure...", "/v1/bridge/plaid"),
	},
	{
		ID:         "bridge.create-speedchex",
		Method:     "POST",
		Path:       "/v1/bridge/speedchex",
		Summary:    "Creates a new paykey using a Speedchex token as the source. This endpoint allows you to create a secure payment...",
		Positional: []string{},
		keywords:   codeOrchKeywords("bridge", "create-speedchex", "Creates a new paykey using a Speedchex token as the source. This endpoint allows you to create a secure payment...", "/v1/bridge/speedchex"),
	},
	{
		ID:         "bridge.create-tan",
		Method:     "POST",
		Path:       "/v1/bridge/tan",
		Summary:    "Create tan",
		Positional: []string{},
		keywords:   codeOrchKeywords("bridge", "create-tan", "Create tan", "/v1/bridge/tan"),
	},
	{
		ID:         "bridge.create-token",
		Method:     "POST",
		Path:       "/v1/bridge/initialize",
		Summary:    "Use this endpoint to generate a session token for use in the Bridge widget.",
		Positional: []string{},
		keywords:   codeOrchKeywords("bridge", "create-token", "Use this endpoint to generate a session token for use in the Bridge widget.", "/v1/bridge/initialize"),
	},
	{
		ID:         "charges.create",
		Method:     "POST",
		Path:       "/v1/charges",
		Summary:    "Use charges to collect money from a customer for the sale of goods or services.",
		Positional: []string{},
		keywords:   codeOrchKeywords("charges", "create", "Use charges to collect money from a customer for the sale of goods or services.", "/v1/charges"),
	},
	{
		ID:         "charges.get",
		Method:     "GET",
		Path:       "/v1/charges/{id}",
		Summary:    "Retrieves the details of an existing charge. Supply the unique charge `id`, and Straddle will return the...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("charges", "get", "Retrieves the details of an existing charge. Supply the unique charge `id`, and Straddle will return the...", "/v1/charges/{id}"),
	},
	{
		ID:         "charges.update",
		Method:     "PUT",
		Path:       "/v1/charges/{id}",
		Summary:    "Change the values of parameters associated with a charge prior to processing. The status of the charge must be...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("charges", "update", "Change the values of parameters associated with a charge prior to processing. The status of the charge must be...", "/v1/charges/{id}"),
	},
	{
		ID:         "charges.cancel.charge",
		Method:     "PUT",
		Path:       "/v1/charges/{id}/cancel",
		Summary:    "Cancel a charge to prevent it from being originated for processing. The status of the charge must be `created`,...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("charges", "charge", "Cancel a charge to prevent it from being originated for processing. The status of the charge must be `created`,...", "/v1/charges/{id}/cancel"),
	},
	{
		ID:         "charges.hold.charge",
		Method:     "PUT",
		Path:       "/v1/charges/{id}/hold",
		Summary:    "Place a charge on hold to prevent it from being originated for processing. The status of the charge must be...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("charges", "charge", "Place a charge on hold to prevent it from being originated for processing. The status of the charge must be...", "/v1/charges/{id}/hold"),
	},
	{
		ID:         "charges.release.charge",
		Method:     "PUT",
		Path:       "/v1/charges/{id}/release",
		Summary:    "Release a charge from an `on_hold` status to allow it to be rescheduled for processing.",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("charges", "charge", "Release a charge from an `on_hold` status to allow it to be rescheduled for processing.", "/v1/charges/{id}/release"),
	},
	{
		ID:         "charges.resubmit.create",
		Method:     "POST",
		Path:       "/v1/charges/{id}/resubmit",
		Summary:    "Resubmit a failed or reversed charge.",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("charges", "create", "Resubmit a failed or reversed charge.", "/v1/charges/{id}/resubmit"),
	},
	{
		ID:         "charges.unmask.charges-v1-get",
		Method:     "GET",
		Path:       "/v1/charges/{id}/unmask",
		Summary:    "Get a charge by id.",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("charges", "charges-v1-get", "Get a charge by id.", "/v1/charges/{id}/unmask"),
	},
	{
		ID:         "customers.create",
		Method:     "POST",
		Path:       "/v1/customers",
		Summary:    "Creates a new customer record and automatically initiates identity, fraud, and risk assessment scores. This endpoint...",
		Positional: []string{},
		keywords:   codeOrchKeywords("customers", "create", "Creates a new customer record and automatically initiates identity, fraud, and risk assessment scores. This endpoint...", "/v1/customers"),
	},
	{
		ID:         "customers.delete",
		Method:     "DELETE",
		Path:       "/v1/customers/{id}",
		Summary:    "Permanently removes a customer record from Straddle. This action cannot be undone and should only be used to satisfy...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("customers", "delete", "Permanently removes a customer record from Straddle. This action cannot be undone and should only be used to satisfy...", "/v1/customers/{id}"),
	},
	{
		ID:         "customers.get",
		Method:     "GET",
		Path:       "/v1/customers/{id}",
		Summary:    "Retrieves the details of an existing customer. Supply the unique customer ID that was returned from your 'create...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("customers", "get", "Retrieves the details of an existing customer. Supply the unique customer ID that was returned from your 'create...", "/v1/customers/{id}"),
	},
	{
		ID:         "customers.list",
		Method:     "GET",
		Path:       "/v1/customers",
		Summary:    "Lists or searches customers connected to your account. All supported query parameters are optional. If none are...",
		Positional: []string{},
		keywords:   codeOrchKeywords("customers", "list", "Lists or searches customers connected to your account. All supported query parameters are optional. If none are...", "/v1/customers"),
	},
	{
		ID:         "customers.update",
		Method:     "PUT",
		Path:       "/v1/customers/{id}",
		Summary:    "Updates an existing customer's information. This endpoint allows you to modify the customer's contact details, PII,...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("customers", "update", "Updates an existing customer's information. This endpoint allows you to modify the customer's contact details, PII,...", "/v1/customers/{id}"),
	},
	{
		ID:         "customers.refresh-review.update",
		Method:     "PUT",
		Path:       "/v1/customers/{id}/refresh_review",
		Summary:    "Updates the decision of a customer's identity validation. This endpoint allows you to modify the outcome of a...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("customers", "update", "Updates the decision of a customer's identity validation. This endpoint allows you to modify the outcome of a...", "/v1/customers/{id}/refresh_review"),
	},
	{
		ID:         "customers.review.get-customer",
		Method:     "GET",
		Path:       "/v1/customers/{id}/review",
		Summary:    "Retrieves and analyzes the results of a customer's identity validation and fraud score. This endpoint provides a...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("customers", "get-customer", "Retrieves and analyzes the results of a customer's identity validation and fraud score. This endpoint provides a...", "/v1/customers/{id}/review"),
	},
	{
		ID:         "customers.review.update-customer",
		Method:     "PATCH",
		Path:       "/v1/customers/{id}/review",
		Summary:    "Updates the status of a customer's identity decision. This endpoint allows you to modify the outcome of a customer...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("customers", "update-customer", "Updates the status of a customer's identity decision. This endpoint allows you to modify the outcome of a customer...", "/v1/customers/{id}/review"),
	},
	{
		ID:         "customers.unmasked.get-customer",
		Method:     "GET",
		Path:       "/v1/customers/{id}/unmasked",
		Summary:    "Retrieves the unmasked details, including PII, of an existing customer. Supply the unique customer ID that was...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("customers", "get-customer", "Retrieves the unmasked details, including PII, of an existing customer. Supply the unique customer ID that was...", "/v1/customers/{id}/unmasked"),
	},
	{
		ID:         "funding-event-payments.get",
		Method:     "GET",
		Path:       "/v1/funding_event_payments/{id}",
		Summary:    "All the payments that made up the funding event",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("funding-event-payments", "get", "All the payments that made up the funding event", "/v1/funding_event_payments/{id}"),
	},
	{
		ID:         "funding-events.create",
		Method:     "POST",
		Path:       "/v1/funding_events/simulate",
		Summary:    "Simulate a funding event for testing. This endpoint can only be used in the sandbox environment.",
		Positional: []string{},
		keywords:   codeOrchKeywords("funding-events", "create", "Simulate a funding event for testing. This endpoint can only be used in the sandbox environment.", "/v1/funding_events/simulate"),
	},
	{
		ID:         "funding-events.get",
		Method:     "GET",
		Path:       "/v1/funding_events/{id}",
		Summary:    "Retrieves the details of an existing funding event. Supply the unique funding event `id`, and Straddle will return...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("funding-events", "get", "Retrieves the details of an existing funding event. Supply the unique funding event `id`, and Straddle will return...", "/v1/funding_events/{id}"),
	},
	{
		ID:         "funding-events.list",
		Method:     "GET",
		Path:       "/v1/funding_events",
		Summary:    "Retrieves a list of funding events for your account. This endpoint supports advanced sorting and filtering options.",
		Positional: []string{},
		keywords:   codeOrchKeywords("funding-events", "list", "Retrieves a list of funding events for your account. This endpoint supports advanced sorting and filtering options.", "/v1/funding_events"),
	},
	{
		ID:         "linked-bank-accounts.create",
		Method:     "POST",
		Path:       "/v1/linked_bank_accounts",
		Summary:    "Creates a new linked bank account associated with a Straddle account. This endpoint allows you to associate external...",
		Positional: []string{},
		keywords:   codeOrchKeywords("linked-bank-accounts", "create", "Creates a new linked bank account associated with a Straddle account. This endpoint allows you to associate external...", "/v1/linked_bank_accounts"),
	},
	{
		ID:         "linked-bank-accounts.get",
		Method:     "GET",
		Path:       "/v1/linked_bank_accounts/{linked_bank_account_id}",
		Summary:    "Retrieves the details of a linked bank account that has previously been created. Supply the unique linked bank...",
		Positional: []string{"linked_bank_account_id"},
		keywords:   codeOrchKeywords("linked-bank-accounts", "get", "Retrieves the details of a linked bank account that has previously been created. Supply the unique linked bank...", "/v1/linked_bank_accounts/{linked_bank_account_id}"),
	},
	{
		ID:         "linked-bank-accounts.list",
		Method:     "GET",
		Path:       "/v1/linked_bank_accounts",
		Summary:    "Returns a list of bank accounts associated with a specific Straddle account. The linked bank accounts are returned...",
		Positional: []string{},
		keywords:   codeOrchKeywords("linked-bank-accounts", "list", "Returns a list of bank accounts associated with a specific Straddle account. The linked bank accounts are returned...", "/v1/linked_bank_accounts"),
	},
	{
		ID:         "linked-bank-accounts.update",
		Method:     "PUT",
		Path:       "/v1/linked_bank_accounts/{linked_bank_account_id}",
		Summary:    "Updates an existing linked bank account's information. This can be used to update account details during onboarding...",
		Positional: []string{"linked_bank_account_id"},
		keywords:   codeOrchKeywords("linked-bank-accounts", "update", "Updates an existing linked bank account's information. This can be used to update account details during onboarding...", "/v1/linked_bank_accounts/{linked_bank_account_id}"),
	},
	{
		ID:         "linked-bank-accounts.cancel.update",
		Method:     "PATCH",
		Path:       "/v1/linked_bank_accounts/{linked_bank_account_id}/cancel",
		Summary:    "Cancels an existing linked bank account. This can be used to cancel a linked bank account before it has been...",
		Positional: []string{"linked_bank_account_id"},
		keywords:   codeOrchKeywords("linked-bank-accounts", "update", "Cancels an existing linked bank account. This can be used to cancel a linked bank account before it has been...", "/v1/linked_bank_accounts/{linked_bank_account_id}/cancel"),
	},
	{
		ID:         "linked-bank-accounts.unmask.get-linked-bank-account-unmasked",
		Method:     "GET",
		Path:       "/v1/linked_bank_accounts/{linked_bank_account_id}/unmask",
		Summary:    "Retrieves the unmasked details of a linked bank account that has previously been created. Supply the unique linked...",
		Positional: []string{"linked_bank_account_id"},
		keywords:   codeOrchKeywords("linked-bank-accounts", "get-linked-bank-account-unmasked", "Retrieves the unmasked details of a linked bank account that has previously been created. Supply the unique linked...", "/v1/linked_bank_accounts/{linked_bank_account_id}/unmask"),
	},
	{
		ID:         "organizations.create",
		Method:     "POST",
		Path:       "/v1/organizations",
		Summary:    "Creates a new organization related to your Straddle integration. Organizations can be used to group related accounts...",
		Positional: []string{},
		keywords:   codeOrchKeywords("organizations", "create", "Creates a new organization related to your Straddle integration. Organizations can be used to group related accounts...", "/v1/organizations"),
	},
	{
		ID:         "organizations.get-by-id",
		Method:     "GET",
		Path:       "/v1/organizations/{organization_id}",
		Summary:    "Retrieves the details of an Organization that has previously been created. Supply the unique organization ID that...",
		Positional: []string{"organization_id"},
		keywords:   codeOrchKeywords("organizations", "get-by-id", "Retrieves the details of an Organization that has previously been created. Supply the unique organization ID that...", "/v1/organizations/{organization_id}"),
	},
	{
		ID:         "organizations.list",
		Method:     "GET",
		Path:       "/v1/organizations",
		Summary:    "Retrieves a list of organizations associated with your Straddle integration. The organizations are returned sorted...",
		Positional: []string{},
		keywords:   codeOrchKeywords("organizations", "list", "Retrieves a list of organizations associated with your Straddle integration. The organizations are returned sorted...", "/v1/organizations"),
	},
	{
		ID:         "paykeys.get",
		Method:     "GET",
		Path:       "/v1/paykeys/{id}",
		Summary:    "Retrieves the details of an existing paykey. Supply the unique paykey `id` and Straddle will return the...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("paykeys", "get", "Retrieves the details of an existing paykey. Supply the unique paykey `id` and Straddle will return the...", "/v1/paykeys/{id}"),
	},
	{
		ID:         "paykeys.list",
		Method:     "GET",
		Path:       "/v1/paykeys",
		Summary:    "Returns a list of paykeys associated with a Straddle account. This endpoint supports advanced sorting and filtering...",
		Positional: []string{},
		keywords:   codeOrchKeywords("paykeys", "list", "Returns a list of paykeys associated with a Straddle account. This endpoint supports advanced sorting and filtering...", "/v1/paykeys"),
	},
	{
		ID:         "paykeys.cancel.update",
		Method:     "PUT",
		Path:       "/v1/paykeys/{id}/cancel",
		Summary:    "Update",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("paykeys", "update", "Update", "/v1/paykeys/{id}/cancel"),
	},
	{
		ID:         "paykeys.refresh-balance.update",
		Method:     "PUT",
		Path:       "/v1/paykeys/{id}/refresh_balance",
		Summary:    "Updates the balance of a paykey. This endpoint allows you to refresh the balance of a paykey.",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("paykeys", "update", "Updates the balance of a paykey. This endpoint allows you to refresh the balance of a paykey.", "/v1/paykeys/{id}/refresh_balance"),
	},
	{
		ID:         "paykeys.refresh-review.update",
		Method:     "PUT",
		Path:       "/v1/paykeys/{id}/refresh_review",
		Summary:    "Updates the decision of a paykey's review validation. This endpoint allows you to refresh the outcome of a paykey's...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("paykeys", "update", "Updates the decision of a paykey's review validation. This endpoint allows you to refresh the outcome of a paykey's...", "/v1/paykeys/{id}/refresh_review"),
	},
	{
		ID:         "paykeys.reveal.get",
		Method:     "GET",
		Path:       "/v1/paykeys/{id}/reveal",
		Summary:    "Retrieves the details of a paykey that has previously been created. Supply the unique paykey ID that was returned...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("paykeys", "get", "Retrieves the details of a paykey that has previously been created. Supply the unique paykey ID that was returned...", "/v1/paykeys/{id}/reveal"),
	},
	{
		ID:         "paykeys.review.get",
		Method:     "GET",
		Path:       "/v1/paykeys/{id}/review",
		Summary:    "Get additional details about a paykey.",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("paykeys", "get", "Get additional details about a paykey.", "/v1/paykeys/{id}/review"),
	},
	{
		ID:         "paykeys.review.update",
		Method:     "PATCH",
		Path:       "/v1/paykeys/{id}/review",
		Summary:    "Update the status of a paykey when in review status",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("paykeys", "update", "Update the status of a paykey when in review status", "/v1/paykeys/{id}/review"),
	},
	{
		ID:         "paykeys.unblock.update",
		Method:     "PATCH",
		Path:       "/v1/paykeys/{id}/unblock",
		Summary:    "Unblocks a paykey that was previously blocked due to an R29 return code. Only paykeys blocked with R29 returns that...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("paykeys", "update", "Unblocks a paykey that was previously blocked due to an R29 return code. Only paykeys blocked with R29 returns that...", "/v1/paykeys/{id}/unblock"),
	},
	{
		ID:         "paykeys.unmasked.get-paykey",
		Method:     "GET",
		Path:       "/v1/paykeys/{id}/unmasked",
		Summary:    "Retrieves the unmasked details of an existing paykey. Supply the unique paykey `id` and Straddle will return the...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("paykeys", "get-paykey", "Retrieves the unmasked details of an existing paykey. Supply the unique paykey `id` and Straddle will return the...", "/v1/paykeys/{id}/unmasked"),
	},
	{
		ID:         "payments.list",
		Method:     "GET",
		Path:       "/v1/payments",
		Summary:    "Search for payments, including `charges` and `payouts`, using a variety of criteria. This endpoint supports advanced...",
		Positional: []string{},
		keywords:   codeOrchKeywords("payments", "list", "Search for payments, including `charges` and `payouts`, using a variety of criteria. This endpoint supports advanced...", "/v1/payments"),
	},
	{
		ID:         "payouts.create",
		Method:     "POST",
		Path:       "/v1/payouts",
		Summary:    "Use payouts to send money to your customers.",
		Positional: []string{},
		keywords:   codeOrchKeywords("payouts", "create", "Use payouts to send money to your customers.", "/v1/payouts"),
	},
	{
		ID:         "payouts.get",
		Method:     "GET",
		Path:       "/v1/payouts/{id}",
		Summary:    "Retrieves the details of an existing payout. Supply the unique payout `id` to retrieve the corresponding payout...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("payouts", "get", "Retrieves the details of an existing payout. Supply the unique payout `id` to retrieve the corresponding payout...", "/v1/payouts/{id}"),
	},
	{
		ID:         "payouts.update",
		Method:     "PUT",
		Path:       "/v1/payouts/{id}",
		Summary:    "Update the details of a payout prior to processing. The status of the payout must be `created`, `scheduled`, or...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("payouts", "update", "Update the details of a payout prior to processing. The status of the payout must be `created`, `scheduled`, or...", "/v1/payouts/{id}"),
	},
	{
		ID:         "payouts.cancel.payout",
		Method:     "PUT",
		Path:       "/v1/payouts/{id}/cancel",
		Summary:    "Cancel a payout to prevent it from being processed. The status of the payout must be `created`, `scheduled`, or...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("payouts", "payout", "Cancel a payout to prevent it from being processed. The status of the payout must be `created`, `scheduled`, or...", "/v1/payouts/{id}/cancel"),
	},
	{
		ID:         "payouts.hold.payout",
		Method:     "PUT",
		Path:       "/v1/payouts/{id}/hold",
		Summary:    "Hold a payout to prevent it from being processed. The status of the payout must be `created`, `scheduled`, or `on_hold`.",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("payouts", "payout", "Hold a payout to prevent it from being processed. The status of the payout must be `created`, `scheduled`, or `on_hold`.", "/v1/payouts/{id}/hold"),
	},
	{
		ID:         "payouts.release.payout",
		Method:     "PUT",
		Path:       "/v1/payouts/{id}/release",
		Summary:    "Release a payout from a `hold` status to allow it to be rescheduled for processing.",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("payouts", "payout", "Release a payout from a `hold` status to allow it to be rescheduled for processing.", "/v1/payouts/{id}/release"),
	},
	{
		ID:         "payouts.resubmit.create",
		Method:     "POST",
		Path:       "/v1/payouts/{id}/resubmit",
		Summary:    "Resubmit a failed or reversed payout.",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("payouts", "create", "Resubmit a failed or reversed payout.", "/v1/payouts/{id}/resubmit"),
	},
	{
		ID:         "payouts.unmask.payouts-v1-get",
		Method:     "GET",
		Path:       "/v1/payouts/{id}/unmask",
		Summary:    "Get a payout by id.",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("payouts", "payouts-v1-get", "Get a payout by id.", "/v1/payouts/{id}/unmask"),
	},
	{
		ID:         "reports.create",
		Method:     "POST",
		Path:       "/v1/reports/total_customers_by_status",
		Summary:    "Create",
		Positional: []string{},
		keywords:   codeOrchKeywords("reports", "create", "Create", "/v1/reports/total_customers_by_status"),
	},
	{
		ID:         "representatives.create",
		Method:     "POST",
		Path:       "/v1/representatives",
		Summary:    "Creates a new representative associated with an account. Representatives are individuals who have legal authority or...",
		Positional: []string{},
		keywords:   codeOrchKeywords("representatives", "create", "Creates a new representative associated with an account. Representatives are individuals who have legal authority or...", "/v1/representatives"),
	},
	{
		ID:         "representatives.get",
		Method:     "GET",
		Path:       "/v1/representatives/{representative_id}",
		Summary:    "Retrieves the details of an existing representative. Supply the unique representative ID, and Straddle will return...",
		Positional: []string{"representative_id"},
		keywords:   codeOrchKeywords("representatives", "get", "Retrieves the details of an existing representative. Supply the unique representative ID, and Straddle will return...", "/v1/representatives/{representative_id}"),
	},
	{
		ID:         "representatives.list",
		Method:     "GET",
		Path:       "/v1/representatives",
		Summary:    "Returns a list of representatives associated with a specific account or organization. The representatives are...",
		Positional: []string{},
		keywords:   codeOrchKeywords("representatives", "list", "Returns a list of representatives associated with a specific account or organization. The representatives are...", "/v1/representatives"),
	},
	{
		ID:         "representatives.update",
		Method:     "PUT",
		Path:       "/v1/representatives/{representative_id}",
		Summary:    "Updates an existing representative's information. This can be used to update personal details, contact information,...",
		Positional: []string{"representative_id"},
		keywords:   codeOrchKeywords("representatives", "update", "Updates an existing representative's information. This can be used to update personal details, contact information,...", "/v1/representatives/{representative_id}"),
	},
	{
		ID:         "representatives.unmask.get",
		Method:     "GET",
		Path:       "/v1/representatives/{representative_id}/unmask",
		Summary:    "Retrieves the unmasked details of a representative that has previously been created. Supply the unique...",
		Positional: []string{"representative_id"},
		keywords:   codeOrchKeywords("representatives", "get", "Retrieves the unmasked details of a representative that has previously been created. Supply the unique...", "/v1/representatives/{representative_id}/unmask"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		out = append(out, map[string]any{
			"endpoint_id": r.ep.ID,
			"method":      r.ep.Method,
			"path":        r.ep.Path,
			"summary":     r.ep.Summary,
			"score":       r.score,
		})
	}
	data, _ := json.Marshal(map[string]any{"count": len(out), "results": out})
	return mcplib.NewToolResultText(string(data)), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call straddle_search first)"), nil
	}

	var ep *codeOrchEndpoint
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			ep = &codeOrchEndpoints[i]
			break
		}
	}
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call straddle_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok {
			path = strings.ReplaceAll(path, "{"+p+"}", fmt.Sprintf("%v", v))
			delete(params, p)
		}
	}

	// Code-orch dispatch has no schema metadata at runtime to bucket params
	// into body vs query, so POST/PUT/PATCH keep the everything-to-body
	// design. DELETE is the one verb where query routing is unambiguous; the
	// previous code built `query` but never passed it.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[k] = fmt.Sprintf("%v", v)
		}
	}

	hdrs, aerr := applyMCPAccount(ep.Method, ep.Path, ep.HeaderOverrides)
	if aerr != nil {
		return mcplib.NewToolResultError(aerr.Error()), nil
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			data, err = c.GetWithHeaders(path, query, hdrs)
		} else {
			data, err = c.Get(path, query)
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(path, query)
		}
	case "POST":
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(path, params, hdrs)
		} else {
			data, _, err = c.Post(path, params)
		}
	case "PUT":
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(path, params, hdrs)
		} else {
			data, _, err = c.Put(path, params)
		}
	case "PATCH":
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(path, params, hdrs)
		} else {
			data, _, err = c.Patch(path, params)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}
