// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press); maintained directly.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/straddle-build/cli/internal/cli"
	"github.com/straddle-build/cli/internal/client"
	"github.com/straddle-build/cli/internal/cliutil"
	"github.com/straddle-build/cli/internal/config"
	"github.com/straddle-build/cli/internal/mcp/cobratree"
	"github.com/straddle-build/cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		var accountErr error
		headers, accountErr = applyMCPAccount(method, pathTemplate, headers)
		if accountErr != nil {
			return mcplib.NewToolResultError(accountErr.Error()), nil
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if len(headers) > 0 {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export STRADDLE_API_KEY=<your-key>" +
					"\n      Get a key at: https://run.pstmn.io/button.svg" +
					"\n      Run 'straddle-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export STRADDLE_API_KEY=<your-key>" +
					"\n      Get a key at: https://run.pstmn.io/button.svg" +
					"\n      Run 'straddle-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export STRADDLE_API_KEY=<your-key>" +
					"\n      Get a key at: https://run.pstmn.io/button.svg" +
					"\n      Run 'straddle-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "straddle-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "straddle-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "straddle",
		"description": "Every Straddle API operation, plus a local payments ledger, offline search, and settlement and return analytics no...",
		"archetype":   "payments",
		"tool_count":  70,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion straddle-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "STRADDLE_API_KEY",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"key_url": "https://run.pstmn.io/button.svg",
		},
		"resources": []map[string]any{
			{
				"name":        "account-settings",
				"description": "Manage account settings",
				"endpoints":   []string{"get-settings"},
				"searchable":  true,
			},
			{
				"name":        "accounts",
				"description": "Accounts represent businesses using Straddle through your platform. Each account must complete automated...",
				"endpoints":   []string{"create", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "bridge",
				"description": "Bridge provides a comprehensive suite of tools for connecting customer bank accounts. Use it to generate secure...",
				"endpoints":   []string{"create", "create-bank-account-paykey", "create-plaid-paykey", "create-speedchex", "create-tan", "create-token"},
				"searchable":  true,
			},
			{
				"name":        "charges",
				"description": "Charges represent attempts to debit money from a customer's bank account using a Paykey. Each charge includes...",
				"endpoints":   []string{"create", "get", "update"},
				"searchable":  true,
			},
			{
				"name":        "customers",
				"description": "Customers represent the end users who send or receive payments through your integration. Each customer undergoes...",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "funding-event-payments",
				"description": "Manage funding event payments",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "funding-events",
				"description": "Funding events represent all money movement between Straddle and an Account's external bank accounts. They are...",
				"endpoints":   []string{"create", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "linked-bank-accounts",
				"description": "Linked bank accounts connect your platform users' external bank accounts to Straddle for settlements and payment...",
				"endpoints":   []string{"create", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "organizations",
				"description": "Organizations are a powerful feature in Straddle that allow you to manage multiple accounts under a single umbrella....",
				"endpoints":   []string{"create", "get-by-id", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "paykeys",
				"description": "Paykeys are secure tokens that link verified customer identities to their bank accounts. Each Paykey includes...",
				"endpoints":   []string{"get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "payments",
				"description": "Payments provide endpoints to filter both Charges and Payouts with multiple different parameters.",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "payouts",
				"description": "Payouts represent transfers from Straddle to customer bank accounts. Create payouts to handle disbursements, process...",
				"endpoints":   []string{"create", "get", "update"},
				"searchable":  true,
			},
			{
				"name":        "reports",
				"description": "Manage reports",
				"endpoints":   []string{"create"},
			},
			{
				"name":        "representatives",
				"description": "Representatives are individuals who have legal authority or significant responsibility within a business entity...",
				"endpoints":   []string{"create", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass page_number parameter for subsequent pages.",
			"Control page size with the page_size parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Settlement reconciliation", "command": "reconcile", "description": "Match synced charges and payouts to their funding events locally, showing what has settled to your account and what...", "rationale": "Requires joining payments and funding_events that only exist together in the local store; the stateless official CLI...", "via": "mcp-command-mirror"},
			{"name": "Payment pipeline & cancel window", "command": "pipeline", "description": "Group synced charges and payouts by lifecycle status and flag which are still cancelable (created/scheduled/on_hold)...", "rationale": "Encodes Straddle's documented status machine and the pending-is-locked rule against the local payment set; no single...", "via": "mcp-command-mirror"},
			{"name": "Return & NSF analysis", "command": "returns", "description": "Surface failed and reversed payments with their ACH reason codes and rank repeat-offender paykeys and customers from...", "rationale": "Aggregates reason codes across many synced payments and joins them to paykeys/customers; the API exposes returns...", "via": "mcp-command-mirror"},
			{"name": "Identity review queue", "command": "review-queue", "description": "List customers and paykeys sitting in review status, oldest first, with age-in-queue so the KYC backlog is triageable.", "rationale": "Combines customers and paykeys filtered by review state and sorts by queue age locally; the API has no unified...", "via": "mcp-command-mirror"},
			{"name": "Cashflow analytics", "command": "cashflow", "description": "Aggregate synced charge volume in versus payout volume out over a date window, including zero-activity days, with...", "rationale": "Time-bucketed aggregation across the full local payment history; the API returns individual payments, not a net-flow...", "via": "mcp-command-mirror"},
			{"name": "Paykey expiry & block monitor", "command": "expiring", "description": "List paykeys approaching their expires_at and blocked paykeys that are unblock-eligible, so payments do not fail on...", "rationale": "Filters the local paykey set by expiry window and block-eligibility; the API lists paykeys but does not surface an...", "via": "mcp-command-mirror"},
			{"name": "Sandbox outcome reference", "command": "sandbox", "description": "Print the deterministic sandbox_outcome values for customers, paykeys, charges, and payouts plus the sandbox test...", "rationale": "Curated reference of Straddle's sandbox simulation contract that an agent would otherwise have to scrape from docs...", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Settlement reconciliation", "insight": "Requires joining payments and funding_events that only exist together in the local store; the stateless official CLI cannot correlate them across calls."},
			{"topic": "Payment pipeline & cancel window", "insight": "Encodes Straddle's documented status machine and the pending-is-locked rule against the local payment set; no single API call returns this view."},
			{"topic": "Return & NSF analysis", "insight": "Aggregates reason codes across many synced payments and joins them to paykeys/customers; the API exposes returns per-payment, not as a ranked offender report."},
			{"topic": "Identity review queue", "insight": "Combines customers and paykeys filtered by review state and sorts by queue age locally; the API has no unified review backlog endpoint."},
			{"topic": "Cashflow analytics", "insight": "Time-bucketed aggregation across the full local payment history; the API returns individual payments, not a net-flow time series."},
			{"topic": "Paykey expiry & block monitor", "insight": "Filters the local paykey set by expiry window and block-eligibility; the API lists paykeys but does not surface an expiring or recoverable view."},
			{"topic": "Sandbox outcome reference", "insight": "Curated reference of Straddle's sandbox simulation contract that an agent would otherwise have to scrape from docs mid-task."},
			{"topic": "Financial data", "insight": "Always use read-only operations for financial queries. Never use create/update tools for payment data without explicit user confirmation."},
			{"topic": "Reconciliation", "insight": "For reconciliation tasks, sync first then use sql for cross-referencing. API pagination over financial records is slow and rate-limited."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
