// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press); maintained directly.

package cli

import (
	"github.com/spf13/cobra"
)

func newBridgeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "bridge",
		Short:  "Bridge provides a comprehensive suite of tools for connecting customer bank accounts. Use it to generate secure...",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBridgeCreateCmd(flags))
	cmd.AddCommand(newBridgeCreateBankAccountPaykeyCmd(flags))
	cmd.AddCommand(newBridgeCreatePlaidPaykeyCmd(flags))
	cmd.AddCommand(newBridgeCreateSpeedchexCmd(flags))
	cmd.AddCommand(newBridgeCreateTanCmd(flags))
	cmd.AddCommand(newBridgeCreateTokenCmd(flags))
	return cmd
}
