// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press); maintained directly.

package cli

import (
	"github.com/spf13/cobra"
)

func newCustomersUnmaskedCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "unmasked",
		Short: "Manage unmasked",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCustomersUnmaskedGetCustomerCmd(flags))
	return cmd
}
