// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPaykeysRevealCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "reveal",
		Short: "Manage reveal",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPaykeysRevealGetCmd(flags))
	return cmd
}
