// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press); maintained directly.

package cliutil

import "testing"

// TestRedactCredentials pins the credential shapes that must be scrubbed from
// user-visible error output while leaving benign prose untouched.
func TestRedactCredentials(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name  string
		input string
		want  string
	}{
		{
			name:  "bearer token",
			input: "upstream echoed Bearer abc123.def456",
			want:  "upstream echoed [REDACTED]",
		},
		{
			name:  "sk key",
			input: "token sk-abcdefghijklmnop failed",
			want:  "token [REDACTED] failed",
		},
		{
			name:  "key parameter",
			input: "request rejected for key=secretvalue",
			want:  "request rejected for [REDACTED]",
		},
		{
			name:  "benign text",
			input: "request rejected for missing page number",
			want:  "request rejected for missing page number",
		},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := RedactCredentials(tc.input); got != tc.want {
				t.Fatalf("RedactCredentials(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}
