// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press); maintained directly.

package config

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL        string            `toml:"base_url"`
	AuthHeaderVal  string            `toml:"auth_header"`
	Headers        map[string]string `toml:"headers,omitempty"`
	AuthSource     string            `toml:"-"`
	AccessToken    string            `toml:"access_token"`
	RefreshToken   string            `toml:"refresh_token"`
	TokenExpiry    time.Time         `toml:"token_expiry"`
	ClientID       string            `toml:"client_id"`
	ClientSecret   string            `toml:"client_secret"`
	Path           string            `toml:"-"`
	StraddleApiKey string            `toml:"api_key"`
	// TemplateVars holds the runtime values for {placeholder} markers in
	// BaseURL and the request path (e.g. Shopify's {shop}/{version}). Populated
	// at Load() time from env vars; consumed by the client's buildURL helper.
	// Stored as a serializable map so non-default values survive a config save.
	TemplateVars map[string]string `toml:"template_vars,omitempty"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://{environment}.straddle.com",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("STRADDLE_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "straddle", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides
	if v := os.Getenv("STRADDLE_API_KEY"); v != "" {
		cfg.StraddleApiKey = v
		cfg.AuthSource = "env:STRADDLE_API_KEY"
	}

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "" || cfg.AccessToken != "") {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.StraddleApiKey != "" {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("STRADDLE_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}

	// Refuse to send credentials over plaintext: the client attaches
	// Authorization to whatever BaseURL resolves to, so a non-https scheme
	// would leak the key on the wire. http stays allowed for loopback hosts
	// only — the Printing Press verifier and tests point STRADDLE_BASE_URL
	// at local http mock servers.
	if err := validateBaseURL(cfg.BaseURL); err != nil {
		return nil, err
	}

	// Endpoint template vars: resolve each {placeholder} in BaseURL or the
	// GraphQL path against the matching env var. Populated even when values
	// are empty so the client's buildURL helper can issue an actionable
	// "export FOO_BAR=..." error instead of silently sending a request to a
	// URL with literal "{shop}" in it. Under PRINTING_PRESS_VERIFY=1 (set by
	// the printing-press verifier in every mock subprocess), an unset
	// template var falls through to "<name>_placeholder" so dry-run legs
	// reach Cobra instead of hitting buildURL's actionable error first.
	// Placeholders with a spec-declared default (server-URL variables) skip
	// the verify branch; the default is a real value that lets verify probe
	// a real-shaped URL.
	if cfg.TemplateVars == nil {
		cfg.TemplateVars = map[string]string{}
	}
	if v := strings.TrimSpace(os.Getenv("STRADDLE_ENVIRONMENT")); v != "" {
		cfg.TemplateVars["environment"] = normalizeEndpointTemplateValue(v)
	} else {
		cfg.TemplateVars["environment"] = "sandbox"
	}
	return cfg, nil
}

// validateBaseURL enforces the https-only transport rule for the API base
// URL. http is tolerated solely for loopback hosts (localhost, 127.0.0.1,
// ::1) so local mock servers and the Printing Press verifier keep working.
// An empty BaseURL passes through: no request can be built from it, so
// there is no credential to leak, and doctor reports it as unconfigured.
// The scheme is checked by prefix because a templated BaseURL (e.g.
// "https://{environment}.straddle.com") does not survive url.Parse; the
// loopback allowance parses the URL, which is fine because loopback
// overrides are always concrete host:port values.
func validateBaseURL(raw string) error {
	if raw == "" {
		return nil
	}
	lower := strings.ToLower(raw)
	if strings.HasPrefix(lower, "https://") {
		return nil
	}
	err := fmt.Errorf("STRADDLE_BASE_URL must use https (got %q); http is allowed only for loopback hosts", raw)
	if !strings.HasPrefix(lower, "http://") {
		return err
	}
	u, parseErr := url.Parse(raw)
	if parseErr != nil {
		return err
	}
	switch u.Hostname() {
	case "localhost", "127.0.0.1", "::1":
		return nil
	}
	return err
}

// normalizeEndpointTemplateValue cleans up a server-URL template value the
// user has likely pasted from a browser address bar; drops the scheme prefix
// and trailing slash so a placeholder like {domain} resolves to a bare host
// whether the user typed `acme.example.com`, `https://acme.example.com`, or
// `https://acme.example.com/`. Applied only to placeholders carrying a
// spec-declared default (server-URL variables); path-positional placeholders
// like {tenant} pass through unchanged because their accepted shapes are
// API-specific.
func normalizeEndpointTemplateValue(v string) string {
	// Strip scheme prefix case-insensitively: users paste `HTTPS://` from
	// some browsers' address bars, and Go's TrimPrefix is exact-match.
	// Callers TrimSpace the env-var value before passing it in.
	if len(v) >= 8 && strings.EqualFold(v[:8], "https://") {
		v = v[8:]
	} else if len(v) >= 7 && strings.EqualFold(v[:7], "http://") {
		v = v[7:]
	}
	return strings.TrimRight(v, "/")
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Env-var token wins over file-stored AccessToken (env > config convention).
	if c.StraddleApiKey != "" {
		c.AuthSource = "env:STRADDLE_API_KEY"
		return "Bearer " + c.StraddleApiKey
	}
	if c.AccessToken != "" {
		c.AuthSource = "oauth2"
		return "Bearer " + c.AccessToken
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	return c.save()
}

func (c *Config) ClearTokens() error {
	// AuthHeader() falls back to the env-var-derived fields when AuthHeaderVal
	// and AccessToken are empty, so dropping the working credential requires
	// zeroing every emitted credential field, not just the OAuth trio.
	// ClientID/ClientSecret persist to disk via SaveTokens for the oauth2
	// and oauth2-cc flows, so logout must wipe them too; otherwise
	// `auth login` can re-mint a new access token unattended.
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	c.StraddleApiKey = ""
	return c.save()
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

// Ensure strings import is used
var _ = strings.ReplaceAll
